gg.setVisible(false)
gg.searchNumber(":/data/user/0/com.tencent", gg.TYPE_BYTE)
gg.getResults(99999)
gg.editAll("116", gg.TYPE_BYTE)
gg.setRanges(gg.REGION_C_ALLOC)
gg.setVisible(false)
gg.searchNumber(":com.tencent.ig", gg.TYPE_BYTE)
gg.getResults(50000)
gg.editAll("101", gg.TYPE_BYTE)
gg.setRanges(gg.REGION_C_ALLOC)
gg.setVisible(false)
gg.searchNumber(":com.pubg.krmobile", gg.TYPE_BYTE)
gg.getResults(50000)
gg.editAll("101", gg.TYPE_BYTE)
gg.setRanges(gg.REGION_C_ALLOC)
gg.setVisible(false)
gg.searchNumber(":com.vng.pubgmobile", gg.TYPE_BYTE)
gg.getResults(50000)
gg.editAll("101", gg.TYPE_BYTE)
gg.setRanges(gg.REGION_C_ALLOC)
gg.setVisible(false)
gg.searchNumber(":com.pubg.krmobile", gg.TYPE_BYTE)
gg.getResults(50000)
gg.editAll("101", gg.TYPE_BYTE)
gg.setRanges(gg.REGION_C_ALLOC)
gg.setVisible(false)
gg.searchNumber(":qos.hk.gcloudcs.com", gg.TYPE_BYTE)
gg.getResults(50000)
gg.editAll("101", gg.TYPE_BYTE)
gg.setRanges(gg.REGION_C_ALLOC)
gg.setVisible(false)
gg.searchNumber(":cloud.gsdk.proximabeta.com", gg.TYPE_BYTE)
gg.getResults(50000)
gg.editAll("101", gg.TYPE_BYTE)
gg.setRanges(gg.REGION_C_ALLOC)
gg.setVisible(false)
gg.searchNumber(":com.tencent.mobileqqu", gg.TYPE_BYTE)
gg.getResults(50000)
gg.editAll("101", gg.TYPE_BYTE)
gg.setRanges(gg.REGION_C_ALLOC)
gg.setVisible(false)
gg.searchNumber(":com.tencent.mobileqqsa", gg.TYPE_BYTE)
gg.getResults(50000)
gg.editAll("101", gg.TYPE_BYTE)
gg.setRanges(gg.REGION_C_ALLOC)
gg.setVisible(false)
gg.searchNumber(":com.tencent.mobileqq", gg.TYPE_BYTE)
gg.getResults(50000)
gg.editAll("101", gg.TYPE_BYTE)
gg.setRanges(gg.REGION_C_ALLOC)
gg.setVisible(false)
gg.searchNumber(":com.professor.go", gg.TYPE_BYTE)
gg.getResults(50000)
gg.editAll("101", gg.TYPE_BYTE)
gg.setRanges(gg.REGION_C_ALLOC)
gg.setVisible(false)
gg.searchNumber(":com.tencent.gamestick", gg.TYPE_BYTE)
gg.getResults(50000)
gg.editAll("101", gg.TYPE_BYTE)
gg.setVisible(false)